### PR TITLE
Ignore warnings so vs code pytest integration works

### PR DESCRIPTION
**Pull request by Jongmassey**
e7cc523 introduced a warning which causes Pytest to error when VS Code Python Testing extension runs `python  -m pytest --collect-only --rootdir tests -s --cache-clear .` to discover the tests in the project. This causes the extension to refuse to load the discovered tests, the change in this PR tells Pytest not to raise an Error on Warnings and thus makes the extension work again

### CODE REVIEW

**Comment by inglesp** [comment]
Raising an error on warning can be very useful.  Better would be to address this particular warning.

One way to do this would be to tell pytest to set the `PYTHONHASHSEED` variable.  You can do this with [pytest-env](https://pypi.org/project/pytest-env/).

(A better way to do it might be to set the environment variable when your virtualenv is activated, but since everyone's setup is different, there's no easy way of applying this to all developers.)

**Comment by Jongmassey** [comment]
good point, how about only ignoring that specific warning?

**Review by iaindillingham — APPROVED** [review]

**Comment by StevenMaude** [comment]
PR with the pytest-env approach: https://github.com/opensafely-core/ehrql/pull/1459

It does fix this problem for me.

**Comment by evansd** [comment]
_Copying this from elsewhere as a comment on a closed PR is likely to get lost._

Unfortunately (and non-obviously), the fix in #1459 won't quite work: it will silence the warning but not address the underlying issue. The problem is that changes to the PYTHONHASHSEED value made after the process starts [don't have any effect](https://stackoverflow.com/questions/30585108/disable-hash-randomization-from-within-python-program) – though the official documentation fails to mention this.

I think  we might be able to fix this for VSCode users by adding a `.env` file with:
```
PYTHONHASHSEED=0
```

It looks like these will be [loaded by default](https://code.visualstudio.com/docs/python/environments#_environment-variables) under the standard configuration.

For developers using different tooling we'll just have to document that variables specified in the `.env` file should be set somehow.

**Pull request closed without merging**
