### PR TITLE
docs: Document `occupation_on_covid_vaccine_record` table

### LINKED ISSUE #1377: Document occupation_on_covid_vaccine_record table
See https://github.com/opensafely-core/ehrql/issues/1340 for details.

### PR DESCRIPTION
**Pull request by StevenMaude**
Fixes #1377.

### CODE REVIEW

**Comment by StevenMaude** [comment]
There was some previous discussion where @wjchulme highlighted that [the meaning of the `is_healthcare_worker` column wasn't entirely understood](https://bennettoxford.slack.com/archives/C33TWNQ1J/p1678448869779779), whether it reflects:

* either, people who've *ever* responded "yes" to this question
* or, a person's most recently recorded response (which means some "yes" respondents could have later switched to "no" at subsequent vaccinations)

It feels like this would be useful contextual information. But I'm unsure if we can add this right now, as not sure a definitive answer was ever reached; I can't find one, at least.

**Comment by StevenMaude** [comment]
Have requested researcher feedback on this PR.

**Comment by wjchulme** [comment]
AFAIK we never found out the answer to this. I will try to raise it with Chris

**Review by inglesp — APPROVED** [review]

**Comment by StevenMaude** [comment]
I'll merge now so that's there's at least some information. We can update the documentation if we learn more about the data.

**Pull request merged**
