### PR TITLE
Clarify behaviour of omitting output option

### PR DESCRIPTION
**Pull request by StevenMaude**
This was discussed in Slack:

https://bennettoxford.slack.com/archives/C02HJTL065A/p1692101347621419?thread_ts=1692095561.720749&cid=C02HJTL065A

### CODE REVIEW

**Comment by sebbacon** [comment]
I wonder if it belongs [here](https://docs.opensafely.org/ehrql/explanation/output-formats/) too?

**Review by sebbacon — APPROVED** [review]
Definitely an improvement.

As a random aside, I'm not a fan of semantic linebreaks (presumably that's what I can see here?). Personal taste I guess but I find it harder to read, not easier.

**Comment by StevenMaude** [comment]
> semantic linebreaks (presumably that's what I can see here?)

Yes, that's what this is.

I didn't like it that much at first, and now I do more, but I'm not really tied to it.

**Comment by StevenMaude** [comment]
There's a bit of a mix of semantic and non-semantic line breaks throughout the ehrQL documentation.

I think the actual benefit is actual more for reading diffs, than when adding new lines; like this [good example](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

**Comment by StevenMaude** [comment]
I'll merge for now anyway, because of this mixture we have.

**Comment by StevenMaude** [comment]
> I wonder if it belongs [here](https://docs.opensafely.org/ehrql/explanation/output-formats/) too?

I didn't see that :man_facepalming: — but it's a very good suggestion, so I'll add in another PR.

**Pull request merged**
